# Generated by Django 3.1.2 on 2020-10-18 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_gymuser_gym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymuser',
            name='gym',
        ),
        migrations.AddField(
            model_name='booking',
            name='classes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='gyms.class'),
            preserve_default=False,
        ),
    ]
