# Generated by Django 3.1.2 on 2020-10-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_auto_20201018_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gymuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
