# Generated by Django 3.1.2 on 2020-10-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_auto_20201018_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='type',
            field=models.CharField(choices=[('1', 'Boxing'), ('2', 'Cardio Box'), ('3', 'Chair Yoga'), ('4', 'Zumba'), ('5', 'spinning'), ('6', 'Arthritis Cycle'), ('7', 'Kettlebell')], max_length=1),
        ),
    ]
