# Generated by Django 3.1.2 on 2020-10-18 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0007_auto_20201018_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='GymUser',
        ),
    ]
