# Generated by Django 3.1.2 on 2020-10-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0008_auto_20201018_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='GymUser',
            new_name='user',
        ),
    ]
