# Generated by Django 3.1.2 on 2020-10-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0010_auto_20201018_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='type',
            field=models.CharField(choices=[('Aerial', 'Aerial'), ('Barre', 'Barre'), ('Bootcamp', 'Bootcamp'), ('Boxing', 'Boxing'), ('Circuit training', 'Circuit training'), ('Crossfit', 'Crossfit'), ('Cycling', 'Cycling')], max_length=40),
        ),
    ]
