# Generated by Django 3.1.2 on 2020-10-18 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0012_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GymUser',
        ),
    ]
